stations = function, { pipeline, function };

pipeline = '-', '>';

function = ( macro | identifier ), '(', [ argument, { ',', argument } ], ')';

macro = identifier, '!';

identifier = ( letter | special ), { letter | special | digit } - ({ letter | special | digit }, '->', { letter | special | digit });

argument = float | integer | relative_reference | variable | string | function | identifier | macro;

variable = argument;

relative_reference = { digit }, '_', { digit };

string = '"', { all_characters - '"' }, '"';

integer = [ '-' ], digit, { digit };

float = integer, '.', digit, { digit };

letter = lower | upper;

special = '_' | '+' | '-' | '*' | '/' | '>' | '<' | '=' | '?' | '!';

lower = 'a' | 'b' | 'c' | 'd' | '...' | 'w' | 'x' | 'y' | 'z';

upper = 'A' | 'B' | 'C' | 'D' | '...' | 'W' | 'X' | 'Y' | 'Z';

digit = '0' | '1' | '...' | '9';